### ISSUE TITLE
Device has an IP address but refuses connections

### ISSUE THREAD

**Issue by inzig0** [anthonymesa/T230NU-Arch-Linux#1]
Hello,
Arch Linux refuses all internet connections. I'm currently using a Motorola Moto G, but other than the rooting process, everything in this guide worked perfectly for me. However, I cannot get Arch Linux to connect anywhere. I used 
`# ip a`
and I can confirm it does have a LAN address (very likely inherited off Android, not sure if this could be the problem), but it still doesn't want to connect anywhere. There is no error or response from ping, it just freezes on a blinking cursor until I use `Ctrl+C` to kill the program. It's possible that it's an issue with the kernel not knowing how to handle packets from a chroot environment, because pinging 127.0.0.1 does the same thing (my Android version is 4.4.2 and the kernel is 3.4.0, if that helps). I'm not sure if this should go here since I don't have the device used in the example, but any help at all would be great. Thanks!

**Comment by anthonymesa** [comment]
What does your /etc/hostname and /etc/hosts look like?

**Comment by inzig0** [comment]
/etc/hostname
`alarm`
/etc/hosts
`# Static table lookup for hostnames.`
`# See hosts(5) for details.`

**Comment by anthonymesa** [comment]
When you say that everything worked except for the rooting process, are you saying that you are using a rooted or unrooted device?

**Comment by inzig0** [comment]
My device is rooted. The reason I said that was because my device isn't the same one in the guide, so the rooting process for me was different.

**Comment by anthonymesa** [comment]
What is the specific model number of your Moto G and your Android build number?

**Comment by Tomodoro** [comment]
Hello @inzig0 

I found a possible solution related to both archlinux arm and Android 4.4 that may help you.

I was trying to get `cadaver` (a WebDAV client) working on my SM-T230 and I always got the connection refused.  I had no issue installing the package nor updating the system multiple times, so I tried a simple `ping archlinux.org` as a baseline test and it didn't work either. I searched online and found [this answer](https://archlinuxarm.org/forum/viewtopic.php?t=4611) that solved the problem. It turns out Android 4.4 has an extra layer of security that manages internet permission through groups. Apply that change to the root account allowed me to get both `cadaver` and `ping` working.

Regards, Tomodoro

**Comment by inzig0** [comment]
@Tomodoro ,
I tried this fix, but sadly, it didn't work. Whenever I try to use any application that requires any network interface, the program locks up at the part where it's supposed to connect. 
@anthonymesa ,
My device's build number is `KXB20.9-1.10-1.18-1.1`.
Under Model number, it says Moto G. However, when using bluetooth it will show up as `XT1031`, and when using `adb devices` it shows up as `TA96510YRP`.

**Comment by Tomodoro** [comment]
I am sorry to hear that, it was the closest thing related to your issue that happened to me.

I support what [anthonymesa says](https://github.com/anthonymesa/T230NU-Arch-Linux/issues/1#issuecomment-870904040), the device is too different from the one in the guide and the variables open up too much. Maybe a specialized forum or someone with a similar device could be of better help for you.

Regards, Tomodoro

**Comment by anthonymesa** [comment]
Yeah, I wish you luck @inzig0, but given that the device is not the same as the guide, I am going to go ahead and close this issue.
